name: GitHub Classroom Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Tests Image
        run: |
          docker build -t tests:latest -f ./Dockerfile . --target=tests
          docker save tests:latest > tests.tar

      - name: Build Release Image
        run: |
          docker build -t person_api:latest -f ./Dockerfile . --target=release
          docker save person_api:latest > person_api.tar

      - name: Upload Tests Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tests-artifact
          path: tests.tar

      - name: Upload API Artifact
        uses: actions/upload-artifact@v4
        with:
          name: person_api-artifact
          path: person_api.tar

#  tests:
#    name: Run Unit Tests
#    runs-on: ubuntu-latest
#    needs: build
#
#    steps:
#      - name: Download Tests Artifact
#        uses: actions/download-artifact@v4
#        with:
#          name: tests-artifact
#          path: .
#
#      - name: Load Image and Run Tests
#        run: |
#          docker load < tests.tar
#          docker compose -f docker-compose.tests.yml up --exit-code-from tests
#
#      - name: List Files Before Tests
#        run: ls -la
#
#      - name: Load Image and Run Tests
#        run: |
#          docker load < tests.tar
#          docker compose -f docker-compose.tests.yml up --exit-code-from tests

  deploy:
    name: Deploy to VDS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download API Artifact
        uses: actions/download-artifact@v4
        with:
          name: person_api-artifact
          path: .

      - name: List Files Before Deploy
        run: ls -la

      - name: Set OpenAPI Host
        run: |
          sed -i "s|http://localhost:8080|http://${{ secrets.HOST }}:8080|g" ./person-service.yaml

      - name: Copy Files to VDS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: |
            docker-compose.yml
            person-service.yaml
            person_api.tar
          target: "/var/www/lab1-rsoi"

      - name: Restart Containers on VDS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/lab1-rsoi
            docker load < person_api.tar
            docker compose down || true
            docker compose up -d