name: GitHub Classroom Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Tests Image
        run: |
          docker build -t tests:latest -f ./Dockerfile . --target=tests
          docker save tests:latest > tests.tar

      - name: Build Release Image
        run: |
          docker build -t person_api:latest -f ./Dockerfile . --target=release
          docker save person_api:latest > person_api.tar

      - name: Upload Tests Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tests-artifact
          path: tests.tar

      - name: Upload API Artifact
        uses: actions/upload-artifact@v4
        with:
          name: person_api-artifact
          path: person_api.tar

  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Tests Artifact
        uses: actions/download-artifact@v4
        with:
          name: tests-artifact
          path: .

      - name: List Files Before Tests
        run: ls -la

      - name: Load Image and Run Tests
        run: |
          docker load < tests.tar
          docker run --rm tests:latest

  deploy:
    name: Deploy to VDS
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download API Artifact
        uses: actions/download-artifact@v4
        with:
          name: person_api-artifact
          path: .

      - name: List Files Before Deploy
        run: ls -la

      - name: Set OpenAPI Host
        run: |
          sed -i "s|http://localhost:8080|http://${{ secrets.HOST }}:8080|g" ./person-service.yaml
      - name: Set Postman baseUrl
        run: |
          sed -i 's|"value": ""|"value": "http://${{ secrets.HOST }}:8080"|g' "postman/[inst][heroku] Lab1.postman_environment.json"


      - name: Copy Files to VDS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/var/www/lab1-rsoi"

      - name: Restart Containers on VDS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/lab1-rsoi
            docker load < person_api.tar
            docker compose down || true
            docker compose up -d
      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'
