name: GitHub Classroom Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build tests image
        run: |
          docker build -t tests:latest -f ./Dockerfile . --target=tests
          docker save tests:latest > tests.tar

      - name: Build release image
        run: |
          docker build -t person_api:latest -f ./Dockerfile . --target=release
          docker save person_api:latest > person_api.tar

      - name: Upload tests artifact
        uses: actions/upload-artifact@v4
        with:
          name: tests-artifact
          path: tests.tar

      - name: Upload api artifact
        uses: actions/upload-artifact@v4
        with:
          name: person_api-artifact
          path: person_api.tar

  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download tests artifact
        uses: actions/download-artifact@v4
        with:
          name: tests-artifact

      - name: Load image and run tests
        run: |
          docker load < tests.tar
          docker run --rm tests:latest

  deploy:
    name: Deploy to VDS
    runs-on: ubuntu-latest
    needs: tests

    steps:


      - name: Download api artifact
        uses: actions/download-artifact@v4
        with:
          name: person_api-artifact
          path: .

      - name: Set OpenAPI host
        run: |
          sed -i "s|http://localhost:8080|http://${{ secrets.HOST }}:8080|g" person-service.yaml

      - name: List files before deploy
        run: ls -la

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to VDS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "./docker-compose.yml ./person-service.yaml ./person_api.tar"
          target: "/var/www/lab1-rsoi"

      - name: Restart containers on VDS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/lab1-rsoi
            docker load < person_api.tar
            docker compose down || true
            docker compose up -d